<?php if ($this->pageCount): ?>
<nav aria-label="Page navigation">
    <ul class="pagination">
        <?php if (isset($this->previous)): ?>
            <li>
                <a href="<?php echo $this->url($this->route, array('page' => $this->previous)); ?>" aria-label="Previous">
                    <span aria-hidden="true">&laquo;</span>
                </a>
            </li>
        <?php else: ?>
            <li class="disabled"><a href="javascript: void(0);" aria-label="Previous"><span aria-hidden="true">&laquo;</span></a></li>
        <?php endif; ?>
        <?php foreach ($this->pagesInRange as $page): ?>
            <?php if ($page != $this->current): ?>
                <li><a href="<?php echo $this->url($this->route, array('page' => $page)); ?>"><?php echo $page; ?></a></li>
            <?php else: ?>
                <li class="disabled">
                    <a href="javascript: void(0);"><?php echo $page; ?></a>
                </li>
            <?php endif; ?>
        <?php endforeach; ?>
        <?php if (isset($this->next)): ?>
            <li>
                <a href="<?php echo $this->url($this->route, array('page' => $this->next)); ?>" aria-label="Next">
                    <span aria-hidden="true">&raquo;</span>
                </a>
            </li>
        <?php else: ?>
            <li class="disabled"><a href="javascript: void(0);" aria-label="Next"><span aria-hidden="true">&raquo;</span></a></li>
        <?php endif; ?>
    </ul>
</nav>
<?php endif; ?>